version: '3.8'

services:
  hwp-converter-web:
    build: .
    environment:
      - TZ=Asia/Seoul
    command: uvicorn app:app --host 0.0.0.0 --port 80 

networks:
  default:
    name: compose-main  
    external: true